language: java

sudo: false
addons:
  apt:
    packages:
    - ant
    - ant-optional
    - junit4
    - libhamcrest-java

cache:
  apt: true

after_success:
  - coveralls

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

